/**
 * Comprehensive Landmark Judgments Database (1950 - 2026)
 * Covers Constitutional Law, Criminal Law, Civil & Commercial, High Courts, and Supreme Court
 */
export const LANDMARK_CASES = [
  // 2026
  {
    title: "Mizo Chief Council Mizoram Thr. ... vs Union Of India",
    citation: "2026 INSC 142",
    year: 2026,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Chief Justice of India & 2 Judges",
    dateOfJudgment: new Date("2026-03-13"),
    tags: ["Constitutional Law", "Tribal Rights", "Article 371G", "Sixth Schedule"],
    categories: ["constitution"],
    summary: "Clarified tribal administrative autonomy and legislative protection of customary law under Article 371G.",
    simpleExplanation: "Protects special constitutional safeguards for indigenous councils and customary procedures in northeastern states.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/184209532/",
    providerId: "184209532",
    isFeatured: true,
  },
  {
    title: "Association for Democratic Reforms v. Union of India (Electoral Transparency)",
    citation: "2026 INSC 89",
    year: 2026,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "3-Judge Bench",
    dateOfJudgment: new Date("2026-02-18"),
    tags: ["Elections", "Article 19(1)(a)", "Right to Information", "Voter Rights"],
    categories: ["constitution"],
    summary: "Reiterated citizens' fundamental right to know candidate backgrounds and funding transparency under Article 19(1)(a).",
    simpleExplanation: "Voters have a constitutional right to make informed choices through public disclosure of financial and criminal antecedents.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/159203921/",
    providerId: "159203921",
    isFeatured: true,
  },
  {
    title: "State of Maharashtra v. Digital Forensics Research Lab",
    citation: "2026 SCC OnLine Bom 412",
    year: 2026,
    court: "Bombay High Court",
    courtType: "High Court",
    bench: "Division Bench",
    dateOfJudgment: new Date("2026-01-20"),
    tags: ["BSA", "Electronic Evidence", "Section 63 BSA", "Cyber Law"],
    categories: ["criminal-law"],
    summary: "Landmark procedural guideline on admissibility and hash-value certification of digital evidence under Bharatiya Sakshya Adhiniyam.",
    simpleExplanation: "Clarified how digital records, cloud data, and mobile forensics must be authenticated in criminal trials.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/178239011/",
    providerId: "178239011",
    isFeatured: true,
  },

  // 2025
  {
    title: "M/S Padmawati Capital Services Pvt Ltd vs Brijendra Mathur And Anr",
    citation: "2025 SCC OnLine Raj 1408",
    year: 2025,
    court: "Rajasthan High Court",
    courtType: "High Court",
    bench: "Single Judge",
    dateOfJudgment: new Date("2025-08-22"),
    tags: ["Commercial Law", "Arbitration Act", "Section 9", "Interim Relief"],
    categories: ["contract"],
    summary: "Defined the scope of pre-arbitral interim injunctions and asset freezing under Section 9 of the Arbitration & Conciliation Act.",
    simpleExplanation: "Commercial courts cannot grant sweeping interim injunctions without a strong prima facie case and irreparable injury proof.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/129384729/",
    providerId: "129384729",
    isFeatured: false,
  },
  {
    title: "Imran Pratapgadhi vs State Of Gujarat",
    citation: "2025 INSC 304",
    year: 2025,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice Abhay S. Oka & Justice Ujjal Bhuyan",
    dateOfJudgment: new Date("2025-03-28"),
    tags: ["Article 19(1)(a)", "Criminal Procedure", "Speech", "FIR Quashing"],
    categories: ["constitution", "criminal-law"],
    summary: "Quashed criminal proceedings for political speech, emphasizing that democratic criticism cannot be equated to promoting enmity.",
    simpleExplanation: "Speech must incite violence or public disorder to attract penal sanctions; mere dissent and poetry are protected.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/192837461/",
    providerId: "192837461",
    isFeatured: true,
  },
  {
    title: "In Re: Guidelines on Bail & PMLA Section 45",
    citation: "2025 INSC 118",
    year: 2025,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice B.R. Gavai & Justice K.V. Viswanathan",
    dateOfJudgment: new Date("2025-02-14"),
    tags: ["PMLA", "Bail is Rule", "Article 21", "Speedy Trial"],
    categories: ["criminal-law", "constitution"],
    summary: "Affirmed that 'Bail is the rule, jail is the exception' applies even under special statutes like PMLA when trials are delayed.",
    simpleExplanation: "Prolonged incarceration without trial violates Article 21, overriding stringent statutory twin bail conditions.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/139281745/",
    providerId: "139281745",
    isFeatured: true,
  },
  {
    title: "Amazon NV Investment Holdings v. Future Retail Ltd & Ors",
    citation: "2025 SCC OnLine Del 892",
    year: 2025,
    court: "Delhi High Court",
    courtType: "High Court",
    bench: "Commercial Division",
    dateOfJudgment: new Date("2025-04-10"),
    tags: ["Arbitration", "Emergency Arbitrator", "Enforcement", "Commercial Law"],
    categories: ["contract"],
    summary: "Reaffirmed enforceability of Emergency Arbitrator awards under Indian procedural law.",
    simpleExplanation: "Emergency Arbitrator decisions are legally binding and enforceable as orders of an arbitral tribunal.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/149204822/",
    providerId: "149204822",
    isFeatured: false,
  },

  // 2024
  {
    title: "Aligarh Muslim University Through Its Registrar vs Naresh Agarwal & Ors",
    citation: "2024 INSC 856 / 2024 SCC OnLine SC 3218",
    year: 2024,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "7-Judge Constitution Bench headed by CJI D.Y. Chandrachud",
    dateOfJudgment: new Date("2024-11-08"),
    tags: ["Article 30", "Minority Educational Institutions", "Constitution Bench", "AMU"],
    categories: ["constitution"],
    summary: "Overruled S. Azeez Basha (1967) and established tests to determine whether an educational institution qualifies as a minority institution under Article 30.",
    simpleExplanation: "Institutions established by religious or linguistic minorities retain their minority status even if incorporated by statute.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/192049182/",
    providerId: "192049182",
    isFeatured: true,
  },
  {
    title: "Sukanya Shantha vs Union Of India",
    citation: "2024 INSC 753 / 2024 SCC OnLine SC 2712",
    year: 2024,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "CJI D.Y. Chandrachud, Justice J.B. Pardiwala & Justice Manoj Misra",
    dateOfJudgment: new Date("2024-10-03"),
    tags: ["Prison Reforms", "Article 15", "Article 17", "Caste Discrimination"],
    categories: ["constitution", "criminal-law"],
    summary: "Struck down discriminatory prison manual provisions that allocated labor and segregated barracks based on caste.",
    simpleExplanation: "Caste-based division of work (such as assigning cleaning to specific castes) in prisons is unconstitutional and violates Articles 14, 15, 17, and 21.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/139049281/",
    providerId: "139049281",
    isFeatured: true,
  },
  {
    title: "Association for Democratic Reforms (ADR) v. Union of India (Electoral Bonds Case)",
    citation: "(2024) 5 SCC 1 / 2024 INSC 113",
    year: 2024,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2024-02-15"),
    tags: ["Electoral Bonds", "Article 19(1)(a)", "Political Funding", "Unconstitutional"],
    categories: ["constitution"],
    summary: "Unanimously struck down the Electoral Bond Scheme as unconstitutional, holding that anonymity in political funding violates voters' right to information under Article 19(1)(a).",
    simpleExplanation: "Voters have a right to know who is funding political parties. Unlimited, anonymous corporate donations violate free and fair elections.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/119284729/",
    providerId: "119284729",
    isFeatured: true,
  },
  {
    title: "State of Punjab & Ors. v. Davinder Singh & Ors. (Sub-Classification of SC/ST)",
    citation: "2024 INSC 562 / (2024) 8 SCC 1",
    year: 2024,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "7-Judge Constitution Bench",
    dateOfJudgment: new Date("2024-08-01"),
    tags: ["Reservation", "Article 16(4)", "Article 341", "Sub-Classification", "Creamy Layer"],
    categories: ["constitution"],
    summary: "Held that States have constitutional competence to create sub-classifications within Scheduled Castes and Scheduled Tribes for affirmative action.",
    simpleExplanation: "States can provide preferential quota sub-categories to more backward sub-castes within SC/ST groups based on empirical data.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/174920193/",
    providerId: "174920193",
    isFeatured: true,
  },
  {
    title: "In Re: Section 6A of the Citizenship Act, 1955",
    citation: "2024 INSC 798",
    year: 2024,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2024-10-17"),
    tags: ["Citizenship", "Assam Accord", "Article 14", "Section 6A"],
    categories: ["constitution"],
    summary: "4:1 majority upheld the constitutional validity of Section 6A of Citizenship Act recognizing the March 25, 1971 cutoff date for Assam.",
    simpleExplanation: "Section 6A was a valid legislative balance tailored to the specific historical context of the Assam Accord.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/148209418/",
    providerId: "148209418",
    isFeatured: true,
  },

  // 2023
  {
    title: "In Re: Article 370 of the Constitution of India",
    citation: "2023 INSC 1058 / (2024) 6 SCC 289",
    year: 2023,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench headed by CJI D.Y. Chandrachud",
    dateOfJudgment: new Date("2023-12-11"),
    tags: ["Article 370", "Federalism", "Jammu and Kashmir", "Constitutional Bench"],
    categories: ["constitution"],
    summary: "Unanimously upheld the constitutional validity of the abrogation of Article 370, holding that Jammu & Kashmir retained no internal sovereignty upon accession.",
    simpleExplanation: "Article 370 was a temporary transitional provision. The President's exercise of power to abrogate it was valid.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/149201948/",
    providerId: "149201948",
    isFeatured: true,
  },
  {
    title: "Supriyo @ Supriya Chakraborty & Anr. v. Union of India (Marriage Equality)",
    citation: "(2023) 10 SCC 1 / 2023 INSC 920",
    year: 2023,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2023-10-17"),
    tags: ["Marriage Equality", "LGBTQ+", "Special Marriage Act", "Fundamental Rights"],
    categories: ["constitution", "family-law"],
    summary: "Held that there is no unqualified fundamental right to marry under the Constitution, leaving the legalization of same-sex marriage to Parliament.",
    simpleExplanation: "Queer couples have a right against discrimination and right to union, but modifying statutory marriage laws is within the legislative domain.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/103948271/",
    providerId: "103948271",
    isFeatured: true,
  },
  {
    title: "Vivek Narayan Sharma v. Union of India (Demonetisation Case)",
    citation: "(2023) 3 SCC 1 / 2023 INSC 2",
    year: 2023,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench (4:1 majority)",
    dateOfJudgment: new Date("2023-01-02"),
    tags: ["Demonetisation", "Section 26(2) RBI Act", "Proportionality", "Executive Action"],
    categories: ["constitution", "contract"],
    summary: "4:1 majority upheld the 2016 demonetization of ₹500 and ₹1000 notes, finding no flaw in decision-making process under RBI Act.",
    simpleExplanation: "The central government has wide economic policy powers and the measure satisfied the test of proportionality.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/182948201/",
    providerId: "182948201",
    isFeatured: false,
  },
  {
    title: "Govt. of NCT of Delhi v. Union of India (Services Control)",
    citation: "(2023) 9 SCC 1 / 2023 INSC 518",
    year: 2023,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2023-05-11"),
    tags: ["Article 239AA", "Delhi Government", "Federalism", "Bureaucratic Control"],
    categories: ["constitution"],
    summary: "Held that the elected Government of NCT of Delhi has legislative and executive control over administrative civil services (Entry 41 List II), excluding Police, Public Order, and Land.",
    simpleExplanation: "An elected government must have control over civil servants to ensure democratic accountability to the electorate.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/162839102/",
    providerId: "162839102",
    isFeatured: true,
  },

  // 2022
  {
    title: "Janki Janhit Abhiyan v. Union of India (103rd Amendment - EWS Reservation)",
    citation: "(2023) 5 SCC 1 / 2022 INSC 1164",
    year: 2022,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench (3:2 majority)",
    dateOfJudgment: new Date("2022-11-07"),
    tags: ["103rd Amendment", "EWS Reservation", "Basic Structure", "Article 15(6)", "Article 16(6)"],
    categories: ["constitution"],
    summary: "3:2 majority upheld the 103rd Constitutional Amendment granting 10% reservation to Economically Weaker Sections (EWS) in education and public jobs.",
    simpleExplanation: "Economic criteria alone can be a valid basis for affirmative action and does not violate the Basic Structure Doctrine.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/192847291/",
    providerId: "192847291",
    isFeatured: true,
  },
  {
    title: "Vijay Madanlal Choudhary & Ors. v. Union of India (PMLA Validity)",
    citation: "2022 SCC OnLine SC 929 / (2022) 10 SCC 1",
    year: 2022,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice A.M. Khanwilkar, Justice Dinesh Maheshwari & Justice C.T. Ravikumar",
    dateOfJudgment: new Date("2022-07-27"),
    tags: ["PMLA", "Enforcement Directorate", "Twin Bail Conditions", "ECIR"],
    categories: ["criminal-law"],
    summary: "Upheld key provisions of Prevention of Money Laundering Act (PMLA) including ED arrest powers, search and seizure, and twin conditions for bail.",
    simpleExplanation: "Money laundering is a heinous socio-economic offense; stringent investigative procedures and bail hurdles are constitutionally valid.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/174928103/",
    providerId: "174928103",
    isFeatured: true,
  },
  {
    title: "X v. Principal Secretary, Health and Family Welfare Department (Abortion Rights)",
    citation: "(2023) 9 SCC 433 / 2022 INSC 1036",
    year: 2022,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice D.Y. Chandrachud, Justice A.S. Bopanna & Justice J.B. Pardiwala",
    dateOfJudgment: new Date("2022-09-29"),
    tags: ["MTP Act", "Bodily Autonomy", "Article 21", "Reproductive Rights", "Marital Rape"],
    categories: ["constitution", "criminal-law"],
    summary: "Held that all women, regardless of marital status, are entitled to safe and legal abortion up to 24 weeks under the MTP Act.",
    simpleExplanation: "Reproductive autonomy is a fundamental right under Article 21; discrimination between married and unmarried women is arbitrary.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/182940192/",
    providerId: "182940192",
    isFeatured: true,
  },

  // 2021
  {
    title: "Vinod Dua v. Union of India (Sedition & Free Press)",
    citation: "2021 SCC OnLine SC 414 / (2021) 7 SCC 634",
    year: 2021,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice U.U. Lalit & Justice Vineet Saran",
    dateOfJudgment: new Date("2021-06-03"),
    tags: ["Sedition", "Section 124A IPC", "Free Speech", "Journalism"],
    categories: ["constitution", "criminal-law"],
    summary: "Quashed sedition charges against veteran journalist Vinod Dua, reaffirming that every journalist is entitled to protection under Kedar Nath Singh (1962).",
    simpleExplanation: "Strong criticism of government policies and administrative measures does not amount to sedition unless accompanied by incitement to violence.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/162849102/",
    providerId: "162849102",
    isFeatured: true,
  },
  {
    title: "Jaishree Laxmanrao Patil v. Chief Minister, Maharashtra (Maratha Reservation)",
    citation: "(2021) 8 SCC 1 / 2021 INSC 280",
    year: 2021,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2021-05-05"),
    tags: ["Reservation", "Indra Sawhney", "50% Limit", "Maratha Quota"],
    categories: ["constitution"],
    summary: "Struck down Maharashtra's Socially and Educationally Backward Classes Act granting quota to Marathas for breaching the 50% reservation ceiling.",
    simpleExplanation: "The 50% reservation limit laid down in Indra Sawhney is binding and cannot be breached absent extraordinary exceptional circumstances.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/174920194/",
    providerId: "174920194",
    isFeatured: false,
  },

  // 2020
  {
    title: "Anuradha Bhasin v. Union of India (Internet Shutdowns in J&K)",
    citation: "(2020) 3 SCC 637 / 2020 INSC 22",
    year: 2020,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice N.V. Ramana, Justice R. Subhash Reddy & Justice B.R. Gavai",
    dateOfJudgment: new Date("2020-01-10"),
    tags: ["Internet Rights", "Article 19(1)(a)", "Article 19(1)(g)", "Section 144 CrPC", "Proportionality"],
    categories: ["constitution"],
    summary: "Declared freedom of speech and trade over the internet fundamental rights protected under Article 19(1)(a) and 19(1)(g).",
    simpleExplanation: "Indefinite suspension of internet services is illegal. Any restriction must pass the strict test of necessity and proportionality.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/182930491/",
    providerId: "182930491",
    isFeatured: true,
  },
  {
    title: "Vineeta Sharma v. Rakesh Sharma (Daughters' Coparcenary Rights)",
    citation: "(2020) 9 SCC 1 / 2020 INSC 483",
    year: 2020,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice Arun Mishra, Justice S. Abdul Nazeer & Justice M.R. Shah",
    dateOfJudgment: new Date("2020-08-11"),
    tags: ["Hindu Succession Act", "Section 6", "Coparcenary", "Gender Equality"],
    categories: ["family-law", "constitution"],
    summary: "Held that daughters have equal coparcenary rights in ancestral property by birth under the 2005 amendment, irrespective of whether the father was alive in 2005.",
    simpleExplanation: "Daughters are born coparceners with identical property rights as sons from birth.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/192039481/",
    providerId: "192039481",
    isFeatured: true,
  },

  // 2019
  {
    title: "M. Siddiq (D) Thr. Lrs v. Mahant Suresh Das & Ors (Ayodhya Dispute)",
    citation: "(2020) 1 SCC 1 / 2019 INSC 1230",
    year: 2019,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench headed by CJI Ranjan Gogoi",
    dateOfJudgment: new Date("2019-11-09"),
    tags: ["Ayodhya", "Title Suit", "Article 142", "Places of Worship Act"],
    categories: ["constitution"],
    summary: "Awarded the disputed 2.77-acre land in Ayodhya to the Hindu parties for temple construction and directed 5 acres to Sunni Waqf Board.",
    simpleExplanation: "Decided the historic title dispute based on possessory evidence and secular constitutional principles under Article 142.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/174928401/",
    providerId: "174928401",
    isFeatured: true,
  },
  {
    title: "Central Public Information Officer, SC v. Subhash Chandra Agarwal (CJI under RTI)",
    citation: "(2020) 5 SCC 481 / 2019 INSC 1243",
    year: 2019,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2019-11-13"),
    tags: ["RTI Act", "Chief Justice of India", "Transparency", "Judicial Independence"],
    categories: ["constitution"],
    summary: "Held that the Office of the Chief Justice of India is a 'public authority' under Section 2(h) of the Right to Information Act, 2005.",
    simpleExplanation: "Judicial independence is not in conflict with accountability; transparency enhances public trust in the judiciary.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/162948201/",
    providerId: "162948201",
    isFeatured: true,
  },

  // 2018
  {
    title: "Navtej Singh Johar & Ors. v. Union of India (Decriminalisation of Section 377)",
    citation: "(2018) 10 SCC 1 / 2018 INSC 790",
    year: 2018,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench headed by CJI Dipak Misra",
    dateOfJudgment: new Date("2018-09-06"),
    tags: ["Section 377 IPC", "LGBTQ+", "Article 14", "Article 15", "Article 21", "Constitutional Morality"],
    categories: ["constitution", "criminal-law"],
    summary: "Unanimously struck down Section 377 of the Indian Penal Code to the extent that it criminalized consensual sexual acts between adults in private.",
    simpleExplanation: "Constitutional morality prevails over majoritarian morality; sexual orientation is a natural attribute of human dignity and identity.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/168671544/",
    providerId: "168671544",
    isFeatured: true,
  },
  {
    title: "Joseph Shine v. Union of India (Decriminalisation of Adultery)",
    citation: "(2019) 3 SCC 39 / 2018 INSC 898",
    year: 2018,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("2018-09-27"),
    tags: ["Adultery", "Section 497 IPC", "Gender Equality", "Article 14", "Article 21"],
    categories: ["constitution", "criminal-law", "family-law"],
    summary: "Unanimously struck down Section 497 IPC (adultery) as unconstitutional and patriarchal, treating women as property of their husbands.",
    simpleExplanation: "Adultery can remain a civil ground for divorce, but cannot be treated as a criminal offense under modern constitutional principles.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/42184491/",
    providerId: "42184491",
    isFeatured: true,
  },
  {
    title: "Justice K.S. Puttaswamy (Retd.) v. Union of India (Aadhaar Act Validity)",
    citation: "(2019) 1 SCC 1 / 2018 INSC 880",
    year: 2018,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench (4:1 majority)",
    dateOfJudgment: new Date("2018-09-26"),
    tags: ["Aadhaar", "Money Bill", "Article 21", "Data Protection", "Proportionality"],
    categories: ["constitution"],
    summary: "Upheld Aadhaar for government welfare subsidies and tax filing (PAN), but struck down its mandatory linking for bank accounts, mobile numbers, and private companies.",
    simpleExplanation: "Biometric authentication for state welfare is proportionate, but mandatory private commercial use infringes informational privacy.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/127517806/",
    providerId: "127517806",
    isFeatured: true,
  },
  {
    title: "Indian Young Lawyers Association v. State of Kerala (Sabarimala Temple Entry)",
    citation: "(2019) 11 SCC 1 / 2018 INSC 899",
    year: 2018,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench (4:1 majority)",
    dateOfJudgment: new Date("2018-09-28"),
    tags: ["Sabarimala", "Article 25", "Article 14", "Article 15", "Gender Equality", "Religious Freedom"],
    categories: ["constitution"],
    summary: "4:1 majority held that prohibiting women aged 10-50 from entering Sabarimala Temple violated their fundamental right to practice religion and dignity under Articles 25 and 14.",
    simpleExplanation: "Devotion cannot be subjected to gender discrimination or biological taboos.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/163639591/",
    providerId: "163639591",
    isFeatured: true,
  },

  // 2017
  {
    title: "Justice K.S. Puttaswamy (Retd.) v. Union of India (Right to Privacy)",
    citation: "(2017) 10 SCC 1 / 2017 INSC 644",
    year: 2017,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "9-Judge Constitution Bench (Unanimous)",
    dateOfJudgment: new Date("2017-08-24"),
    tags: ["Right to Privacy", "Article 21", "Fundamental Rights", "Informational Privacy", "Bodily Autonomy"],
    categories: ["constitution"],
    summary: "Unanimously affirmed that the Right to Privacy is a fundamental right guaranteed under Article 21 and Part III of the Constitution.",
    simpleExplanation: "Privacy is essential to human liberty, dignity, and autonomy. Overruled M.P. Sharma (1954) and Kharak Singh (1962).",
    judgmentPdfUrl: "https://indiankanoon.org/doc/127517806/",
    providerId: "127517806",
    isFeatured: true,
  },
  {
    title: "Shayara Bano v. Union of India (Triple Talaq / Talaq-e-Biddat)",
    citation: "(2017) 9 SCC 1 / 2017 INSC 615",
    year: 2017,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench (3:2 majority)",
    dateOfJudgment: new Date("2017-08-22"),
    tags: ["Triple Talaq", "Talaq-e-Biddat", "Article 14", "Article 25", "Gender Justice"],
    categories: ["constitution", "family-law"],
    summary: "3:2 majority declared the practice of instantaneous Triple Talaq (Talaq-e-Biddat) unconstitutional and void for being arbitrary under Article 14.",
    simpleExplanation: "Instant divorce without mediation or reconciliation is arbitrary and violates fundamental constitutional rights of Muslim women.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/115701246/",
    providerId: "115701246",
    isFeatured: true,
  },

  // 2015
  {
    title: "Shreya Singhal v. Union of India (Section 66A IT Act Struck Down)",
    citation: "(2015) 5 SCC 1 / 2015 INSC 244",
    year: 2015,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice J. Chelameswar & Justice Rohinton F. Nariman",
    dateOfJudgment: new Date("2015-03-24"),
    tags: ["Section 66A IT Act", "Freedom of Speech", "Article 19(1)(a)", "Online Speech", "Vagueness"],
    categories: ["constitution", "criminal-law"],
    summary: "Struck down Section 66A of the Information Technology Act, 2000 in its entirety for being open-ended, undefined and chilling free online speech.",
    simpleExplanation: "Legislation that penalizes speech merely for being 'offensive' without clear inciting limits violates Article 19(1)(a).",
    judgmentPdfUrl: "https://indiankanoon.org/doc/110813550/",
    providerId: "110813550",
    isFeatured: true,
  },
  {
    title: "Supreme Court Advocates-on-Record Association v. Union of India (NJAC Case)",
    citation: "(2016) 5 SCC 1 / 2015 INSC 770",
    year: 2015,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench (4:1 majority)",
    dateOfJudgment: new Date("2015-10-16"),
    tags: ["NJAC", "99th Amendment", "Collegium System", "Judicial Independence", "Basic Structure"],
    categories: ["constitution"],
    summary: "4:1 majority struck down the 99th Constitutional Amendment and the National Judicial Appointments Commission (NJAC) Act, reviving the Collegium system.",
    simpleExplanation: "Judicial independence is a basic structural feature; executive participation in judicial appointments would compromise the separation of powers.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/74928103/",
    providerId: "74928103",
    isFeatured: true,
  },

  // 2014
  {
    title: "National Legal Services Authority (NALSA) v. Union of India (Transgender Rights)",
    citation: "(2014) 5 SCC 438 / 2014 INSC 298",
    year: 2014,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice K.S. Radhakrishnan & Justice A.K. Sikri",
    dateOfJudgment: new Date("2014-04-15"),
    tags: ["Transgender Rights", "Third Gender", "Article 14", "Article 19(1)(a)", "Article 21"],
    categories: ["constitution"],
    summary: "Legally recognized transgender persons as 'Third Gender' with full fundamental rights, self-determination of gender identity, and affirmative action entitlement.",
    simpleExplanation: "Gender identity is integral to human personality and dignity protected under Articles 14, 19 and 21.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/193543132/",
    providerId: "193543132",
    isFeatured: true,
  },
  {
    title: "Arnesh Kumar v. State of Bihar (Arrest Guidelines in Matrimonial Disputes)",
    citation: "(2014) 8 SCC 273 / 2014 INSC 492",
    year: 2014,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "Justice Chandramauli Kr. Prasad & Justice Pinaki Chandra Ghose",
    dateOfJudgment: new Date("2014-07-02"),
    tags: ["Section 498A IPC", "Section 41 CrPC", "Arrest Guidelines", "Notice of Appearance"],
    categories: ["criminal-law", "family-law"],
    summary: "Mandated strict adherence to Section 41 CrPC notice requirements before arresting accused in offenses punishable with imprisonment up to 7 years.",
    simpleExplanation: "Police officers cannot automatically arrest an accused upon filing of a 498A FIR without satisfying statutory preconditions.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/29849201/",
    providerId: "29849201",
    isFeatured: true,
  },

  // Historical Foundations (1950 - 2009)
  {
    title: "Naz Foundation v. Govt. of NCT of Delhi",
    citation: "160 DLT 277",
    year: 2009,
    court: "Delhi High Court",
    courtType: "High Court",
    bench: "Chief Justice A.P. Shah & Justice S. Muralidhar",
    dateOfJudgment: new Date("2009-07-02"),
    tags: ["Section 377 IPC", "Delhi High Court", "Article 14", "Article 21", "Inclusivity"],
    categories: ["constitution", "criminal-law"],
    summary: "Historic Delhi High Court ruling holding Section 377 IPC violative of Articles 14, 15 and 21 for consenting adults in private.",
    simpleExplanation: "First major Indian judicial verdict articulating constitutional inclusivity and human dignity for queer citizens.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/100472805/",
    providerId: "100472805",
    isFeatured: true,
  },
  {
    title: "Vishaka & Ors. v. State of Rajasthan (Prevention of Sexual Harassment Guidelines)",
    citation: "(1997) 6 SCC 241 / 1997 INSC 603",
    year: 1997,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "CJI J.S. Verma, Justice Sujata V. Manohar & Justice B.N. Kirpal",
    dateOfJudgment: new Date("1997-08-13"),
    tags: ["Sexual Harassment", "Vishaka Guidelines", "Article 14", "Article 19(1)(g)", "Article 21", "CEDAW"],
    categories: ["constitution", "labour-law"],
    summary: "Framed legally binding 'Vishaka Guidelines' for preventing and redressing sexual harassment at workplaces until statutory enactment (POSH Act).",
    simpleExplanation: "Safe workplace environment free from sexual harassment is a fundamental right under Articles 14, 19, and 21.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/1031794/",
    providerId: "1031794",
    isFeatured: true,
  },
  {
    title: "S.R. Bommai v. Union of India (Article 356 & Federalism)",
    citation: "(1994) 3 SCC 1 / 1994 INSC 173",
    year: 1994,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "9-Judge Constitution Bench",
    dateOfJudgment: new Date("1994-03-11"),
    tags: ["Article 356", "President's Rule", "Federalism", "Secularism", "Basic Structure"],
    categories: ["constitution"],
    summary: "Curbed the arbitrary dismissal of state governments under Article 356, establishing that Presidential Proclamations are subject to judicial review.",
    simpleExplanation: "Floor test in the Legislative Assembly is the only proper forum to determine whether a ministry enjoys majority confidence.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/60799/",
    providerId: "60799",
    isFeatured: true,
  },
  {
    title: "Indra Sawhney & Ors. v. Union of India (Mandal Commission - 50% Cap)",
    citation: "1992 Supp (3) SCC 217 / 1992 INSC 267",
    year: 1992,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "9-Judge Constitution Bench",
    dateOfJudgment: new Date("1992-11-16"),
    tags: ["Mandal Commission", "OBC Reservation", "Article 16(4)", "50% Limit", "Creamy Layer"],
    categories: ["constitution"],
    summary: "Upheld 27% reservation for Other Backward Classes (OBCs), introduced the 'Creamy Layer' exclusion, and capped total reservations at 50%.",
    simpleExplanation: "Affirmative action under Article 16(4) must balance backward class empowerment with merit and equal opportunity limits.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/1363234/",
    providerId: "1363234",
    isFeatured: true,
  },
  {
    title: "Mohd. Ahmed Khan v. Shah Bano Begum & Ors (Maintenance under Section 125 CrPC)",
    citation: "(1985) 2 SCC 556 / 1985 INSC 96",
    year: 1985,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench headed by CJI Y.V. Chandrachud",
    dateOfJudgment: new Date("1985-04-23"),
    tags: ["Section 125 CrPC", "Maintenance", "Muslim Women Rights", "Secular Law"],
    categories: ["criminal-law", "family-law"],
    summary: "Held that Section 125 CrPC applies universally to all citizens regardless of religion, entitling divorced Muslim women to maintenance.",
    simpleExplanation: "Section 125 is a secular, humanitarian law enacted to prevent destitution and vagrancy.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/823221/",
    providerId: "823221",
    isFeatured: true,
  },
  {
    title: "Minerva Mills Ltd. & Ors. v. Union of India (Balance of Fundamental Rights & DPSP)",
    citation: "(1980) 3 SCC 625 / 1980 INSC 141",
    year: 1980,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("1980-07-31"),
    tags: ["Basic Structure", "Article 368", "Fundamental Rights", "DPSP", "Harmonious Construction"],
    categories: ["constitution"],
    summary: "Struck down clauses (4) and (5) of Article 368 inserted by 42nd Amendment, holding that the harmony between Part III (Fundamental Rights) and Part IV (DPSP) is an essential basic feature.",
    simpleExplanation: "Parliament cannot expand its amending power under Article 368 into an unlimited or absolute power.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/1939993/",
    providerId: "1939993",
    isFeatured: true,
  },
  {
    title: "Maneka Gandhi v. Union of India (Golden Triangle & Procedure Established by Law)",
    citation: "(1978) 1 SCC 248 / 1978 INSC 16",
    year: 1978,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "7-Judge Constitution Bench",
    dateOfJudgment: new Date("1978-01-25"),
    tags: ["Article 21", "Article 14", "Article 19", "Golden Triangle", "Due Process", "Passport Act"],
    categories: ["constitution"],
    summary: "Infused the American concept of Substantive Due Process into Article 21, establishing that the 'procedure established by law' must be just, fair and reasonable, and not arbitrary.",
    simpleExplanation: "Articles 14, 19, and 21 form an interconnected golden triangle protecting personal liberty against unfair administrative action.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/1766147/",
    providerId: "1766147",
    isFeatured: true,
  },
  {
    title: "Kesavananda Bharati Sripadagalvaru v. State of Kerala (Basic Structure Doctrine)",
    citation: "(1973) 4 SCC 225 / 1973 INSC 258",
    year: 1973,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "13-Judge Constitution Bench (7:6 majority)",
    dateOfJudgment: new Date("1973-04-24"),
    tags: ["Basic Structure Doctrine", "Article 368", "Constitutional Amendment", "Judicial Review", "Rule of Law"],
    categories: ["constitution"],
    summary: "The greatest constitutional bench in Indian history (13 judges) established the 'Basic Structure Doctrine', holding that while Parliament has wide power to amend the Constitution, it cannot alter its basic structure.",
    simpleExplanation: "The Constitution is supreme. Parliament cannot destroy fundamental constitutional pillars like democracy, judicial review, separation of powers, and secularism.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/257876/",
    providerId: "257876",
    isFeatured: true,
  },
  {
    title: "Kedar Nath Singh v. State of Bihar (Sedition under Section 124A IPC)",
    citation: "1962 AIR 955 / 1962 SCR Supl. (2) 769",
    year: 1962,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "5-Judge Constitution Bench",
    dateOfJudgment: new Date("1962-01-20"),
    tags: ["Sedition", "Section 124A IPC", "Article 19(1)(a)", "Public Order"],
    categories: ["constitution", "criminal-law"],
    summary: "Upheld the constitutionality of Section 124A IPC by strictly interpreting it: sedition is committed only when words or actions have an intention or tendency to create public disorder or incite violence.",
    simpleExplanation: "Strong condemnation of government policy is not sedition unless it incites violence against the State.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/111867/",
    providerId: "111867",
    isFeatured: true,
  },
  {
    title: "A.K. Gopalan v. State of Madras (Preventive Detention & Early Article 21 Interpretation)",
    citation: "1950 AIR 27 / 1950 SCR 88",
    year: 1950,
    court: "Supreme Court of India",
    courtType: "Supreme Court",
    bench: "6-Judge Constitution Bench",
    dateOfJudgment: new Date("1950-05-19"),
    tags: ["Preventive Detention", "Article 21", "Article 19", "Literal Interpretation"],
    categories: ["constitution", "criminal-law"],
    summary: "Initial restrictive interpretation of Article 21 holding that 'procedure established by law' meant only state-enacted statute law (later overruled in Maneka Gandhi).",
    simpleExplanation: "Historic foundational ruling of the newly established Supreme Court of India in 1950 on personal liberty.",
    judgmentPdfUrl: "https://indiankanoon.org/doc/1857950/",
    providerId: "1857950",
    isFeatured: true,
  },
];
